# Unveiling the Numbers: Analyzing Winning Probabilities in the 6/49 Lottery

The goal of our analysis is to develop a logical core for a possible mobile app that aids individuals with gambling addictions in estimating their chances of winning the 6/49 lottery. Our approach involves building functions to address key inquiries, such as the probability of winning the grand prize with a single ticket, the probability of winning with multiple tickets, and the probability of having a certain number of winning numbers on a single ticket.

Throughout our project, we made findings that showcase the effectiveness of our approach. We determined that the likelihood of winning the grand prize with any combination of six numbers is extremely low, approximately 0.000007%. Additionally, we created a function enabling app users to compare their ticket against historical lottery data from Canada, allowing them to ascertain if they would have won in the past. Furthermore, we developed a function to calculate the winning probabilities for any number of tickets, providing users with a comprehensive understanding of their chances.

Our analysis also incorporated the calculation of probabilities for winning smaller prizes, specifically two, three, four, or five numbers out of the six drawn. By presenting these essential results concisely, we ensure that our findings are effectively communicated and easily digestible.

## Core Functions

Throughout the project, we'll need to calculate repeatedly probabilities and combinations. We'll start by writing the function that calculates combinations.

In the 6/49 lottery, six numbers are drawn from a set of 49 numbers that range from 1 to 49. The drawing is done without replacement, which means once a number is drawn, it's not put back in the set.

In [132]:
# Function to calculate combinations
def combinations(n, k):
    n_fact = 1
    k_fact = 1
    n_k_fact = 1
    for number in range(1, n+1):
        n_fact = n_fact * number
        if number == k:
            k_fact = n_fact
        if number == n - k:
            n_k_fact = n_fact
    return n_fact / (k_fact * n_k_fact)

In [133]:
combinations(49, 6)

13983816.0

In the 6/49 lottery, six numbers are drawn from a set of 49 numbers that range from 1 to 49. A player wins the big prize if the six numbers on their tickets match all the six numbers drawn.

For the first version of the app, we want players to be able to calculate the probability of winning the big prize with the various numbers they play on a single ticket (for each ticket a player chooses six numbers out of 49). So, we'll start by building a function that calculates the probability of winning the big prize for any given ticket.

In [134]:
def one_ticket_probability(numbers):
    ticket_prob = (1 / combinations(49, 6))*100
    print('Your chance of winning the big prize with the numbers', numbers, ' is ',  f'{ticket_prob:.6f}', '%')
    
one_ticket_probability([1,2,3,4,5,6])

Your chance of winning the big prize with the numbers [1, 2, 3, 4, 5, 6]  is  0.000007 %

## Historical Data Check

Users of the app should also be able to compare their ticket against the historical lottery data in Canada and determine whether they would have ever won by now.

In [135]:
import pandas as pd

# Reading in the data set
lottery = pd.read_csv('649.csv')
lottery

,PRODUCT,DRAW NUMBER,SEQUENCE NUMBER,DRAW DATE,NUMBER DRAWN 1,NUMBER DRAWN 2,NUMBER DRAWN 3,NUMBER DRAWN 4,NUMBER DRAWN 5,NUMBER DRAWN 6,BONUS NUMBER
0,649,1,0,6/12/1982,3,11,12,14,41,43,13
1,649,2,0,6/19/1982,8,33,36,37,39,41,9
2,649,3,0,6/26/1982,1,6,23,24,27,39,34
3,649,4,0,7/3/1982,3,9,10,13,20,43,34
4,649,5,0,7/10/1982,5,14,21,31,34,47,45
...,...,...,...,...,...,...,...,...,...,...,...
3660,649,3587,0,6/6/2018,10,15,23,38,40,41,35
3661,649,3588,0,6/9/2018,19,25,31,36,46,47,26
3662,649,3589,0,6/13/2018,6,22,24,31,32,34,16
3663,649,3590,0,6/16/2018,2,15,21,31,38,49,8
3664,649,3591,0,6/20/2018,14,24,31,35,37,48,17

In [136]:
# Extracting all winning numbers into a new column
lottery['numbers'] = lottery.apply(lambda x: set(x[4:10]), axis=1)
lottery

,PRODUCT,DRAW NUMBER,SEQUENCE NUMBER,DRAW DATE,NUMBER DRAWN 1,NUMBER DRAWN 2,NUMBER DRAWN 3,NUMBER DRAWN 4,NUMBER DRAWN 5,NUMBER DRAWN 6,BONUS NUMBER,numbers
0,649,1,0,6/12/1982,3,11,12,14,41,43,13,"{3, 41, 11, 12, 43, 14}"
1,649,2,0,6/19/1982,8,33,36,37,39,41,9,"{33, 36, 37, 39, 8, 41}"
2,649,3,0,6/26/1982,1,6,23,24,27,39,34,"{1, 6, 39, 23, 24, 27}"
3,649,4,0,7/3/1982,3,9,10,13,20,43,34,"{3, 9, 10, 43, 13, 20}"
4,649,5,0,7/10/1982,5,14,21,31,34,47,45,"{34, 5, 14, 47, 21, 31}"
...,...,...,...,...,...,...,...,...,...,...,...,...
3660,649,3587,0,6/6/2018,10,15,23,38,40,41,35,"{38, 40, 41, 10, 15, 23}"
3661,649,3588,0,6/9/2018,19,25,31,36,46,47,26,"{36, 46, 47, 19, 25, 31}"
3662,649,3589,0,6/13/2018,6,22,24,31,32,34,16,"{32, 34, 6, 22, 24, 31}"
3663,649,3590,0,6/16/2018,2,15,21,31,38,49,8,"{2, 38, 15, 49, 21, 31}"
3664,649,3591,0,6/20/2018,14,24,31,35,37,48,17,"{35, 37, 14, 48, 24, 31}"

In [137]:
# Checking if any number has won more than once
unique_sets = set(map(frozenset, lottery['numbers'].tolist()))

duplicate_sets = list(filter(lambda s: lottery['numbers'].tolist().count(s) > 1, unique_sets))

duplicate_sets

[]

In [138]:
# Converting date to date time format
lottery['date'] = pd.to_datetime(lottery['DRAW DATE'])

In [139]:
# Function to check whether the user's numbers have already won in the past
def check_historical_occurence(numbers):
    numbers_1 = set(numbers)
    if numbers_1 in lottery['numbers'].tolist():
        draw_date = lottery[lottery['numbers'] == numbers_1]['date'].item().strftime('%B %-d, %Y')
        print('The numbers', numbers, 'have won on', draw_date)
    else:
        print('The numbers', numbers, 'have never won before')
    print('Your chance of winning the big prize with these numbers is',
          f'{(1 / combinations(49, 6))*100:.6f}', '%')

In [140]:
check_historical_occurence([4,9,15,16,23,42])

The numbers [4, 9, 15, 16, 23, 42] have never won before
Your chance of winning the big prize with these numbers is 0.000007 %

## Multi-ticket Probability

Lottery addicts usually play more than one ticket on a single drawing, thinking that this might increase their chances of winning significantly. Now we're going to write a function that will allow the users to calculate the chances of winning for any number of different tickets.

In [141]:
def multi_ticket_probability(n):
    # n is a number of different tickets played
    if n <= combinations(49, 6):
        # checking if the number is no more than maximum number of different playable tickets at once
        result = (n / combinations(49, 6))*100
        print('If you play', n, 'ticket(-s), your chance of winning the big prize is',
          f'{result:.6f}', '%')
    else:
        print('There are only', int(combinations(49, 6)), 'different tickets!')

In [142]:
multi_ticket_probability(100)

If you play 100 ticket(-s), your chance of winning the big prize is 0.000715 %

## Less Winning Numbers

In most 6/49 lotteries there are smaller prizes if a player's ticket match two, three, four, or five of the six numbers drawn. As a consequence, the users might be interested in knowing the probability of having two, three, four, or five winning numbers.

We're going to write one more function to allow the users to calculate probabilities for two, three, four, or five winning numbers.

In [143]:
def probability_less_6(n):
    # The functions takes n, the number of winning numbers (between 2 and 5), 
    # and prints information about the chances of winning depending on the value of that integer
    
    combinations_1 = combinations(6, n)
    # Calculating number of n combinations of 6 numbers
    
    # For each one of n-number combinations above, there are (49 minus n) possible successful
    # outcomes in a lottery drawing, minus 1 combination that wins the big prize.
    outcomes = combinations_1 * (49 - n - 1)
    
    result = (outcomes / combinations(49, 6))*100
    print('Your chance of having exactly', n, 'winning numbers for a single lottery ticket is',
          f'{result:.6f}', '%')

In [144]:
probability_less_6(5)

Your chance of having exactly 5 winning numbers for a single lottery ticket is 0.001845 %

# Conclusion

In conclusion, our project aimed to create a logical core for a mobile app that assists individuals with gambling addictions by providing them with valuable insights into their chances of winning the 6/49 lottery. Through our analysis, we successfully developed functions that address key inquiries, including the probability of winning the grand prize with a single ticket, the probability of winning with multiple tickets, and the probability of obtaining various numbers of winning numbers on a single ticket.

Throughout our investigation, we made significant findings that shed light on the challenging odds faced by lottery players. The chance of winning the grand prize with any combination of six numbers was found to be extremely low, approximately 0.000007%. We also implemented a function that enables users of the app to compare their tickets against historical lottery data, allowing them to determine if they would have ever won in the past. Additionally, our project provided users with the ability to calculate winning probabilities for any number of tickets, empowering them with a comprehensive understanding of their chances.

By effectively communicating our findings in a concise manner, we hope to raise awareness about the probabilities involved in lottery games and assist individuals in making informed decisions. Through the logical core we developed, the app can serve as a valuable tool for individuals struggling with gambling addictions, allowing them to better estimate their chances and potentially seek appropriate support.